# -*- coding: utf-8 -*-
"""ALDA_pd3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-vlr_qElqjoEs_8lPOByxz-E92FSWEYF
"""


import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly
import plotly.graph_objects as go

path_players ="./data2/player_final.csv"

df_players = pd.read_csv(path_players)
# df_players.shape

df1 = df_players[['ilkid','weight','height','start_age','position','retirement_age','career_span','lastseason','firstseason']]
# df1.isna().sum()

df2 = df1.dropna(subset=['weight','height','start_age','position','retirement_age','career_span','lastseason','firstseason'])

# df2.isna().sum()

id = df2['ilkid'].copy()
df2 = df2.drop(['ilkid'], axis = 1)

# df2.head()



df_C = df2.loc[df2['position']=='C' ]
df_F = df2.loc[df2['position']=='F' ]
df_G = df2.loc[df2['position']=='G' ]

print('C position analysis')
print(df_C.describe())
print('\n\n')
print('F position analysis')
print(df_F.describe())
print('\n\n')
print('G position analysis')
print(df_G.describe())

# Outcome = Tall players have longer career span





