# -*- coding: utf-8 -*-
"""ALDA_pd2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V6KIly_88LTbyavbUFxDO8EvYTUMxAvs
"""

# HOW POSITION IS CORRELATED with WEIGHT, HEIGHT, AGE



import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly
import plotly.graph_objects as go


path_players ="./data/player_data.csv"

df_players = pd.read_csv(path_players)
df1 = df_players[['ilkid','weight','height','age','position','retirement_age','lastseason','firstseason']]
# df1.shape
df1.isna().sum()

df2 = df1.dropna(subset=['weight','height','age','position','retirement_age','lastseason','firstseason'])
df2.isna().sum()

(unique, counts) = np.unique(df2['position'], return_counts=True)
frequencies = np.asarray((unique, counts)).T
print(frequencies)

df_C = df2.loc[df2['position']=='C' ]
df_F = df2.loc[df2['position']=='F' ]
df_G = df2.loc[df2['position']=='G' ]

df3 = df2[['weight','height']]
X = df3.values
from sklearn.preprocessing import StandardScaler
X = StandardScaler().fit_transform(X)
df3_x = pd.DataFrame(data = X, columns = ['weight','height'])

df_position = df2['position']



plt.figure()
plt.figure(figsize=(6,4))
plt.xlabel('weight')
plt.ylabel('height')
plt.title('weight vs height')
plt.scatter(df3_x['weight'], df3_x['height'])



# CORRELATION BETWEEN WEIGHT AND HEIGHT = 0.82
df3_x.corr()['weight'].sort_values()

# POSITION OF PLAYERS WRT TO THEIR WEIGHT AND HEIGHT
fig, ax = plt.subplots()
colors = {'C':'red', 'F':'green', 'G':'blue'}
ax.scatter(df3_x['weight'], df3_x['height'], c=df_position.map(colors))

plt.xlabel("Weight")
plt.ylabel("Height")
plt.show()

